name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Display Go version
        run: go version

      - name: Builds
        run: |
          mkdir output
          export CGO_ENABLED=0
          GOOS=windows GOARCH=amd64 go build -o output/stalwart-import_windows-amd64.exe ./cmd/import/
          GOOS=linux GOARCH=amd64 go build -o output/stalwart-import_linux-amd64.exe ./cmd/import/
          GOOS=linux GOARCH=arm64 go build -o output/stalwart-import_linux-arm64.exe ./cmd/import/
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            output/*
